version: "3"

services:

  valentine:
    restart: always
    image: kaitoryouga/valentine:latest
    expose:
        - 8080
    environment:
      HTTP_PORT: 8080
      VIRTUAL_HOST: love.kaito.ninja
      LETSENCRYPT_HOST: love.kaito.ninja
      LETSENCRYPT_EMAIL: "kaito1477800@gmail.com"
    networks:
      service_network:

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 5

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  web-redirect:
    image: adamkdean/redirect
    environment:
      VIRTUAL_HOST: kaito.ninja
      LETSENCRYPT_HOST: kaito.ninja
      LETSENCRYPT_EMAIL: "kaito1477800@gmail.com"
      REDIRECT_LOCATION: "https://kaito.ninja"
    networks:
      service_network:
    
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

networks:
  service_network:
  internal:
    internal: true

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  db_data: